name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'main_v*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@c68f6a352f4c822b1feff40bb1045a3e52e41060
        with:
          args: --volume,/home/runner/work/BetonQuest/BetonQuest/.mvn:/root/.m2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}