version: "1.0"
linter: jetbrains/qodana-jvm-community:2023.1

include:
  - name: Deprecation
  - name: DeprecatedIsStillUsed
  - name: DanglingJavadoc
  - name: JavadocLinkAsPlainText
  - name: MissingJavadoc
  - name: NullableProblems